pool: 

  name: default



variables:

   - group: globalgroup123

   - name : pipeline

     value: "i am pipe line variable"

   - name : pipeline1

     value: "i am pipe line1 variable"

parameters:

  - name: param1

    



stages:

 - stage: teststage

   jobs:

    - job : job1

      pool: 

          name: default

      steps:

          - script :

             echo 'test stage job1 Step 1 $(pipeline)'

          - script :

             echo 'test stage job1 Step 2  $(param1)'

 - stage: buildstage

   jobs:

    - job : job1

      pool: 

          name: default

      steps:

          - script :

             echo 'build stage job1 Step 1'

          - script :

             echo 'bhuild stage job1 Step 2'